version: '3'

services:

  db:
    build:
      context: ./mysql
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pa55word
      MYSQL_DATABASE: tech_support
      MYSQL_USER: ts_user
      MYSQL_PASSWORD: pa55word
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
      - mysql:/var/lib/mysql

  web:
    build:
      context: ./php
    container_name: php-webserver
    links:
      - db:db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8080:80"

volumes:
  mysql:
