version: '3.7'

services:

    apache-php:
      image: 'php:apache'
      restart: always
      ports: 
        - 8080:80
      volumes:
        - type: bind
          source: ./apache-php/ch06_tech_support
          target: /var/www/html

    db:
      image: 'mysql:5.7'
      restart: always
      volumes:
        - type: bind
          source: ./database
          target: /var/lib/mysql
      environment:
        MYSQL_DATABASE: characters
        MYSQL_USER: 'csci459'
        MYSQL_PASSWORD: 'csci459'
        MYSQL_RANDOM_ROOT_PASSWORD: '1'